### ISSUE TITLE
Mise en place de l'architecture de l'API

### ISSUE THREAD

**Issue by Weiko** [speakproject/api#16]
Faire une installation propre du projet
- Package.json
- MVC
- etc...

**Comment by edeuxk** [comment]
done

**Comment by Weiko** [comment]
J'ai une proposition d'architecture sur __features/16-architecture__ et j'en ai profité pour intégrer un framework de test unitaires, Mocha : 
*mv routes to controllers folder* : 3e81f6c9a4a1cb1eaa633198273f6c540906d6e5
*Add javascript test framework Mocha* : 306aa37c1ce1e4b1abd5277bcc2169c2a3044944
*Add documentation folder* : e1265a0284e00f2db76dda46ccddb0d30fb6bbb2
*fix routes path* : 867b71953cc232f7b787c3a2a1fc0e94bf445dc7
*add models folder* : 560d6c921a6b8cce881baea31d6a1810b80abd5c
*Add config folder* : 01d997ea0083eb5bbec8678c87f1bb2da586a17f

**Comment by edeuxk** [comment]
Je confirme c'est tout propre.
